import React,{useState,useEffect} from 'react';import {View,Text,FlatList,TextInput,Switch,TouchableOpacity,StyleSheet,Alert} from 'react-native';import * as Notifications from 'expo-notifications';import * as BackgroundFetch from 'expo-background-fetch';import * as TaskManager from 'expo-task-manager';import AsyncStorage from '@react-native-async-storage/async-storage';

const BG_TASK='jake-2h-alert';const API='https://jake-analysis-backend.onrender.com';
TaskManager.defineTask(BG_TASK,async()=>{try{const r=await fetch(`${API}/api/analysis/2h-alert`);const j=await r.json();await Notifications.scheduleNotificationAsync({content:{title:'📊 Jake Analysis 2H',body:j.alertText},trigger:null});const waPhone=await AsyncStorage.getItem('wa_phone');const waKey=await AsyncStorage.getItem('wa_key');if(waPhone&&waKey){await fetch(`${API}/api/notify/whatsapp?phone=${waPhone}&key=${waKey}&text=${encodeURIComponent(j.alertText)}`);}return BackgroundFetch.BackgroundFetchResult.NewData}catch(e){return BackgroundFetch.BackgroundFetchResult.Failed}});

export default function App(){const [assets,setAssets]=useState([]);const [waPhone,setWaPhone]=useState('');const [waKey,setWaKey]=useState('');const [enabled,setEnabled]=useState(true);
useEffect(()=>{(async()=>{await Notifications.requestPermissionsAsync();await BackgroundFetch.registerTaskAsync(BG_TASK,{minimumInterval:7200,stopOnTerminate:false,startOnBoot:true});const r=await fetch(`${API}/api/crypto/all`);const j=await r.json();setAssets(j.data);const p=await AsyncStorage.getItem('wa_phone');if(p)setWaPhone(p);})();},[]);
const saveWa=async()=>{await AsyncStorage.setItem('wa_phone',waPhone);await AsyncStorage.setItem('wa_key',waKey);Alert.alert('Saved','WhatsApp settings saved');};
return(<View style={s.c}><Text style={s.h}>Jake Analysis - ALL Coins + ALL Stocks</Text><Text style={s.sub}>2H Alerts • {assets.length} assets</Text><FlatList data={assets.slice(0,30)} keyExtractor={i=>i.symbol} renderItem={({item})=><View style={s.card}><Text style={s.sym}>{item.symbol}</Text><Text>${item.price} ({item.change}%)</Text></View>}/><View style={s.set}><Text style={s.st}>Settings - 2H WhatsApp Alerts</Text><Text>WhatsApp Number</Text><TextInput value={waPhone} onChangeText={setWaPhone} placeholder='+234...' style={s.inp}/><Text>CallMeBot API Key</Text><TextInput value={waKey} onChangeText={setWaKey} placeholder='apikey' style={s.inp}/><View style={{flexDirection:'row',alignItems:'center'}}><Text>2H Alerts ON</Text><Switch value={enabled} onValueChange={setEnabled}/></View><TouchableOpacity onPress={saveWa} style={s.btn}><Text style={{color:'#fff'}}>Save Settings</Text></TouchableOpacity></View></View>)} 
const s=StyleSheet.create({c:{flex:1,backgroundColor:'#0a0e12',padding:20,paddingTop:50},h:{color:'#00ff88',fontSize:22,fontWeight:'bold'},sub:{color:'#888',marginBottom:10},card:{backgroundColor:'#1a222c',padding:12,marginBottom:8,borderRadius:8,flexDirection:'row',justifyContent:'space-between'},sym:{color:'#fff',fontWeight:'bold'},set:{backgroundColor:'#1a222c',padding:15,borderRadius:10,marginTop:10},st:{color:'#fff',fontWeight:'bold',marginBottom:8},inp:{backgroundColor:'#0a0e12',color:'#fff',padding:10,borderRadius:6,marginBottom:8},btn:{backgroundColor:'#00ff88',padding:12,borderRadius:6,alignItems:'center',marginTop:8}});
